server:
  port: 8083
  
spring:
  cloud:
    gateway:
      routes:
      - uri: http://192.168.20.141:8080
        predicates:
        - Path=/gtw-i/rest/expediente/**
        filters:
        - RewritePath=/gtw-i/rest/expediente/(?<segmento>.*), /sgd-api/rest/expediente?$\{segmento}
management:
  endpoints:
    web:
      exposure:
        include: '*'
