server:
  port: 8083
  
spring:
  cloud:
    gateway:
      routes:
      - id: sgd-api
        uri: http://localhost:8082
        predicates:
        - Path=/weqweqweqw/**
        filters:
        - RewritePath=/weqweqweqw/(?<segmento>.*), /sgd-api/$\{segmento}
