server:
  port: 8084
  
spring:
  cloud:
    gateway:
      routes:
      - uri: http://localhost:8081
        predicates:
        - Path=/gtw-e/**
        filters:
        - RewritePath=/gtw-e/(?<segmento>.*), /mgd-b/$\{segmento}
management:
  endpoints:
    web:
      exposure:
        include: '*'
