server:
  port: 8084
  
spring:
  cloud:
    gateway:
      routes:
      - id: mgd
        uri: http://localhost:8081
        predicates:
        - Path=/gate/**
        filters:
        - RewritePath=/gate/(?<segmento>.*), /mgd-b/$\{segmento}
