server:
  port: 8083
  
spring:
  cloud:
    gateway:
      routes:
      - id: sgd-api
        uri: http://localhost:8082
        predicates:
        - Path=/gtw-i/**
        filters:
        - RewritePath=/gtw-i/(?<segmento>.*), /sgd-api/$\{segmento}
management:
  endpoints:
    web:
      exposure:
        include: '*'
