server:
  port: 8084
  
spring:
  cloud:
    gateway:
      routes:      
      - uri: http://192.168.99.1:8087
        predicates:
        - Path=/gtw-app/**
        filters:
        - RewritePath=/gtw-app/(?<segmento>.*), /sgdfd-msa/$\{segmento}
management:
  endpoints:
    web:
      exposure:
        include: '*'
