server:
  port: 8084
  
spring:
  cloud:
    gateway:
      routes:
      - uri: http://localhost:8081/mgd-b
        predicates:
        - Path=/gtw-app/**
        filters:
        - RewritePath=/gtw-app/(?<segmento>.*), /$\{segmento}
management:
  endpoints:
    web:
      exposure:
        include: '*'
