server:
  port: 8095
  
spring:
  cloud:
    gateway:
      routes:      
      - uri: http://172.16.242.26:9090
        predicates:
        - Path=/gtw-app/**
        filters:
        - RewritePath=/gtw-app/(?<segmento>.*), /sgdfd-ssa/$\{segmento}
management:
  endpoints:
    web:
      exposure:
        include: '*'
