server:
  port: 8084
  
spring:
  cloud:
    gateway:
      routes:
      - uri: http://localhost:8081
        predicates:
        - Path=/gtw-app/**
        filters:
        - RewritePath=/gtw-app/(?<segmento>.*), /mgd-b/$\{segmento}
      - uri: http://localhost:8087
        predicates:
        - Path=/gtw-app/**
        filters:
        - RewritePath=/gtw-app/(?<segmento>.*), /sgdfd-msa/$\{segmento}
management:
  endpoints:
    web:
      exposure:
        include: '*'
